MyMVC/MyMVC/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyMVC.Models;

namespace MyMVC.Controllers
{
    public class NewController : Controller
    {
        //
        // GET: /New/

        public ActionResult Index()
        {
            GetData1 obj = new GetData1();            
            return View(obj);
        }

        [HttpGet]
        public ActionResult Create()
        {
            Default obj = new Default();
            return View(obj);
        }

        [HttpPost]
        public ActionResult Create(Default obj)
        {
            Default df = new Default();
            if (df.SaveData(obj.name) > 0)
            {
                return Redirect("/New/Create");
            }
            else
            {
                return Redirect("/New/Create");
            }
            
        }

        public string NewDisplay()
        {
            return "Hi! Thanks for visiting the WbSite.";
        }
    }
}

MyMVC/MyMVC/Views/New/Create.cshtml
@model MyMVC.Models.Default

@{
    ViewBag.Title = "Create";
}

<h2>Create A Product</h2>

<table>
@foreach (System.Data.DataRow a in Model.GetData().Rows)
{
    <tr><td>
    @Html.Label(a["vName"].ToString())
    </td></tr>
}
</table>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Product</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-label">
            @Html.TextBoxFor(model => model.name)
        </div>
        <input type="submit" value="submit" />
    </fieldset>
}

MyMVC/MyMVC/Views/New/Index.cshtml
@model MyMVC.Models.GetData1

@foreach (System.Data.DataRow a in Model.Stu().Rows)
{
    var id = a["ID"].ToString();
    @Html.Label(id);
}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>@ViewBag.Title</title>
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")"></script>
</head>
<body>
<ul id="menu">
<li>@Html.ActionLink("Home", "Create", "New")</li>
<li>@Html.ActionLink("Movies", "Index", "Movies")</li>
<li>@Html.ActionLink("About", "About", "Home")</li>
</ul> 
<section id="main">
<p>Copyright W3schools 2012. All Rights Reserved.</p>
</section>
</body>
</html>